apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: jvm-resources.yaml
    target:
      kind: Deployment
      name: ".*-service"
  - path: mysql-resources.yaml
    target:
      kind: Deployment
      name: mysql
