apiVersion: v1
kind: Secret
metadata:
    name: bank-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:DeBDtxRPdkqbEMw5EmeEiS03YkuVyXdHN7edYX5bBUk=,iv:cOOI1B4VE0M9TMnpyzdSPhx9BdLMKXQKOSZLES+1evI=,tag:7NLB7smW4FEasVau22qKIw==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:mHS87U8t9w==,iv:nqFzDWlxK/OVHhAtLJ0zxizNqK0kmQ36oOsvWQlSK3w=,tag:OciY8beltX0Xa48ejUk3HQ==,type:str]
    MYSQL_PWD: ENC[AES256_GCM,data:XdEQVudQTDQoBXRP+t9/JurCizcJVURk26drdSnwxw==,iv:WB8lqcWDq6aAbzGPfPbE+koRLgKphtEc6hjP2HlxOhQ=,tag:CtHuIMYL+dtONWUUrplSuw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:9iSLSKToT0yVg5oaCO13qfsmCjEFVN/BJ6B8UcIv7/a2ip/MTLSCGaKHOhaffFCYTzWJgnEED5HZ+8l/Ytg=,iv:U2DJe3QGzwcqRJES2AVoYv7KLMAX9ZjUn8HQCyu+7o0=,tag:BxUwfm/LjXhHoxGhSU2EBw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:hM0yVQ==,iv:oVUmokQCQWkUc5Zg0N5rXVv0DuXa40eAPBDQzqXIhA8=,tag:O8uSh+yd2uXeUuZg71CoVg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:N4VRYA==,iv:ySRxX2YocX0QT8mPpNEL4/Bemajxlp2V4t0+eAgtjUI=,tag:bQCTi4jI3fPwQ+6Gtf9q5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOVoxMU9KSmFpMEkreUJv
            bmNnSkp4VG45emV0MjN3NEJQNndCdVJ0NVVZCkwyOXFjSDFGQy8vb0hCUVVkT2dz
            LzdDajR5VWRrMUw0VUczYTY0QnhpRzQKLS0tIGZKdnVnMVRGME1tcWxkQUQzemtD
            bDY5ZVVBdVp5MXNDb0loK2ZwSk1UNHcKDnsogz03AFyM3X7qz6N7vkuc77NbSk3c
            p+U8XE7SOrYOYkJ2nqrQitcExtQXMMvJz4TDUZNwgF/Ohvi/c2+93w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138jvrc2mjep4dzmrgzsnkpaw27w8gnf6pjfu465700x5uf23k3pssedue9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T11:04:50Z"
    mac: ENC[AES256_GCM,data:VWYfG2F1MUtF4n3lKb37pKqEg3fZgs0npOJQ3ZWdG6ScCl+9h9KDeiSFT5+hkwKQqdNLtNyYlDJ5PMOeY8BVWzvuL3FRZ8tkDRm18LfQ2qTapKq+XOyDCl2U9J5xGbNJajy8sCYjZQ433RCCNQrm1mKAL1dV/GLG+GVd7w/SrfU=,iv:ynq/vPe2lsMlDad441rdebrDCz+s+9XT+p77I8igrtI=,tag:m7f9DiImS0z9WyM8QVeazg==,type:str]
    version: 3.13.3
