apiVersion: v1
kind: Secret
metadata:
    name: bank-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:DeBDtxRPdkqbEMw5EmeEiS03YkuVyXdHN7edYX5bBUk=,iv:cOOI1B4VE0M9TMnpyzdSPhx9BdLMKXQKOSZLES+1evI=,tag:7NLB7smW4FEasVau22qKIw==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:LH4isQ==,iv:caDwpEYwteS1R6WYgUtc4j3ZJgnGr1KwR+R++kjHOHw=,tag:L+ABNp96j5nzMMvEFXKb9w==,type:str]
    MYSQL_PWD: ENC[AES256_GCM,data:S0Jc/pE5gXFrpMu7Pl/UuESuDUGPru+d7eSXvPeGtFs=,iv:0F8Q32gjqicn/0LtSDrGuIEdNNlSQViiJRSmiqP60KU=,tag:B9egRB6hVhe8ZTVVKsbbjA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:9iSLSKToT0yVg5oaCO13qfsmCjEFVN/BJ6B8UcIv7/a2ip/MTLSCGaKHOhaffFCYTzWJgnEED5HZ+8l/Ytg=,iv:U2DJe3QGzwcqRJES2AVoYv7KLMAX9ZjUn8HQCyu+7o0=,tag:BxUwfm/LjXhHoxGhSU2EBw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:hM0yVQ==,iv:oVUmokQCQWkUc5Zg0N5rXVv0DuXa40eAPBDQzqXIhA8=,tag:O8uSh+yd2uXeUuZg71CoVg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:N4VRYA==,iv:ySRxX2YocX0QT8mPpNEL4/Bemajxlp2V4t0+eAgtjUI=,tag:bQCTi4jI3fPwQ+6Gtf9q5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOVoxMU9KSmFpMEkreUJv
            bmNnSkp4VG45emV0MjN3NEJQNndCdVJ0NVVZCkwyOXFjSDFGQy8vb0hCUVVkT2dz
            LzdDajR5VWRrMUw0VUczYTY0QnhpRzQKLS0tIGZKdnVnMVRGME1tcWxkQUQzemtD
            bDY5ZVVBdVp5MXNDb0loK2ZwSk1UNHcKDnsogz03AFyM3X7qz6N7vkuc77NbSk3c
            p+U8XE7SOrYOYkJ2nqrQitcExtQXMMvJz4TDUZNwgF/Ohvi/c2+93w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138jvrc2mjep4dzmrgzsnkpaw27w8gnf6pjfu465700x5uf23k3pssedue9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:40:08Z"
    mac: ENC[AES256_GCM,data:gRToY3oJIJIIG/0kYF/cFHHMQesYRfvHhLcbpbhsVauP85dLfhy8L+jgorIxEucXzNOFxhMXAO6wbnbOdWm3AM1NDljyCIb6u0djL24wW8/fJMsSVylU0xbtcFsCSCGJ0nNWa/wo12ZPgfmsWEjcH5fVkWaUG7C0YzMp4AZ0bBk=,iv:dfEASwGA8oF2SWZUSpwGJRBjveMsvjBZHf/q0y6dGTk=,tag:uzDHYXfZ3G/wvvRgpjrQeQ==,type:str]
    version: 3.13.3
